PORT = 4569

# only postgres db is supported
DB_URL = "postgres://user:password@localhost:5432/mydatabase"

# add cors website (or remove if you want to allow all origins)
cors = ["https://example.com", "https://menu.example.com"]

# configuration needed to generate secure tokens
[token]
access_public_key = """\
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo5g4igiMkseZ9Qj1Zv8O
8DhrSyt6lgtWdhr4pZYKskTIpBzKFCq2DsaZHrKGAQGzLB7le/pzprWy8NDxNYUt
bCga8tq1ZX9QTLE9M2TR98cMWEJfLOzhl5F1DSYt5Hqn9/iIn7W581tylL1Fo1Ts
fyYSlwiWPyGDDPmoJ/h+q2YM+3FsqzinuWv+M4TD41NZip2/HFEbnNx23lp3Hcp1
jj0p4TobYMc7dhnZYLXU3oI4ocKqAVxIfZNTCTY+Kdmvos8CSigf/Xf7RyjLWE/U
0Uy9O5Zb1PVNZIZE2YqMiL9uN1s7l9/J6wMEnmoyQJYZCXdWYMBfj1hcshqWvuYO
BwIDAQAB
-----END PUBLIC KEY-----""" 
access_secret_key = """\
-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAo5g4igiMkseZ9Qj1Zv8O8DhrSyt6lgtWdhr4pZYKskTIpBzK
FCq2DsaZHrKGAQGzLB7le/pzprWy8NDxNYUtbCga8tq1ZX9QTLE9M2TR98cMWEJf
LOzhl5F1DSYt5Hqn9/iIn7W581tylL1Fo1TsfyYSlwiWPyGDDPmoJ/h+q2YM+3Fs
qzinuWv+M4TD41NZip2/HFEbnNx23lp3Hcp1jj0p4TobYMc7dhnZYLXU3oI4ocKq
AVxIfZNTCTY+Kdmvos8CSigf/Xf7RyjLWE/U0Uy9O5Zb1PVNZIZE2YqMiL9uN1s7
l9/J6wMEnmoyQJYZCXdWYMBfj1hcshqWvuYOBwIDAQABAoIBAE9oPNFrcuhwMF/L
GGsFFPgvOo1DLn6URESRtO2TFeAQGR/nxYLidHpZlctbtkXY0GJzIMr795UNDy1r
Dhn/advc36/Pz0rT8GM5iM5gerZ9jJVuqgoBdUL/3MQkKxSDIPLxVUfIitkAI27l
LF8qgpz5Gv7qsRs1pgnvSNsV+E4zNQsS/7LdPz8bLPZ21RpTMWqNekgYVVe5UYBj
Oz4TouVfbqkxto3vJLb+5aiM1ZPWjwBCkpMFV6ZXoX6i7RgqcIHTOBAIskfds9Mu
QJKavnDHc8onUEi/yoMIKT63ins+TH67Wp8xeNqFeRpvlLVjmArJHKz9DGBHNxSo
aLdRhxkCgYEA0qzqd0xhMOzXDPK5i0YxDIu9FdB1nEu5W7yumBBiNaMnXDBS4Zaq
dOpW+lnNWUN/LAQybHOSxhWnRaD75dS/NogfZqzBlg977yZWXtzp5Ko4+u5EBmBc
wJs3R3BvrMIqJOJ+/RpNpVApxnRz8+1pTZih/9v5jqc7S568PxeB9csCgYEAxspM
QOnrZZtV59D1fYHoJLIUsq7kt14WnUlfOsaQ13YWaCJas6f2C65gc+L40Xu89OKA
hFO9sLKoQNQmY6uwx4iJdqaHQ/voLCZ4gKynksn+BJ3qs8WiSQ09imVv4OuSRU62
ljyDjWyMbJMjOl2iY8kW4aKxB0f+v68XpE8NITUCgYA/sA5hajGnfLG2NFprBBkn
1cafpZkoWqv6U5vkVG+cD2qCsAkeMVHubjlFDYjKh2EWiV5E8ttYDou2vOfpntr/
PT9g5rDPEHdC4LATlW0Pt3XqRcVCuDbR8xpO+mqIK1paNC53jVATvZwjZmj3QLoo
vw+aLYHP4jZGsgHugMjE6QKBgQCPWTPxn30zEPe6qdFNBw963rvUOhAONpgCJfW4
8ZVi+fGgeB2F7fmcZMuC5cpdbWhOAsOAKM7iC4MO9K0WNKnOySOvXtit6op6w+cj
it1wGZ7Gf4XOyxaCrTySfyFVRSp+NguufMa0hfEhHl1J6ll+sXSBkwsrX/xRB5b5
0lN6fQKBgQC1/Qd5bvdzMpzwRtKVInf5LrIkCVaS7KYaiBjFeUH26e46Und9OVis
KdMT6LCwiKodYyU5qQdo0/xCtzfxrNbN21x2x3cBAU7ZYDbwYexukPrz5yhUOus0
cOIc5mw88rsBTQz05bDNoR5lWzQFyfBYCwhIiU0I80JWrzrMHFX61g==
-----END RSA PRIVATE KEY-----""" 
access_token_duration = 900 # (15 minutes) in seconds
refresh_public_key = """\
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwhfzyqvjIcIpmrsWr4om
i4oAcxD1pSC86tt6VVntg7TRd0YAO/gZmhzRQVsWSXhQZpe96V/QTbzuYpv2LwId
4ZuQdJ4lJx7pL6WAqH4eMtxoRdaXZlT6CSvgf0dTk398lytsqoOipsYsxyhEXbKm
WPHBe+7/9v50xE4WdC6FEteP0QwdseLU3JSpqs27XMacRemUpU8B25R0kmMmaU2q
idnp2wHJ8WNVqywF8lJslWIWZl6AlWsKbDwysdJTfTi1GA22VmWKXldQ/T6YThD9
dnnw41L1VYcGrEDKhWL91YDTvjT6D4RVX4xEv8JjzYaax9CcsR2P1UpQcQs1TNOY
FwIDAQAB
-----END PUBLIC KEY-----""" 
refresh_secret_key = """\
-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAwhfzyqvjIcIpmrsWr4omi4oAcxD1pSC86tt6VVntg7TRd0YA
O/gZmhzRQVsWSXhQZpe96V/QTbzuYpv2LwId4ZuQdJ4lJx7pL6WAqH4eMtxoRdaX
ZlT6CSvgf0dTk398lytsqoOipsYsxyhEXbKmWPHBe+7/9v50xE4WdC6FEteP0Qwd
seLU3JSpqs27XMacRemUpU8B25R0kmMmaU2qidnp2wHJ8WNVqywF8lJslWIWZl6A
lWsKbDwysdJTfTi1GA22VmWKXldQ/T6YThD9dnnw41L1VYcGrEDKhWL91YDTvjT6
D4RVX4xEv8JjzYaax9CcsR2P1UpQcQs1TNOYFwIDAQABAoIBAQCkrRXXOwc2uTn7
YgjZXuldMvU2q4j/VUt0KEse53GxcVTXUbkZKGLwcsrIHLRIGaB9qvkibHybuFS5
rYGuWKlppUdm6lazXnKSTmVej8KnfIGr32oNFMQfy+5pjubGGkBnMhy8f3sc7L9J
Kkz3AoBIrrVupVTfBv2jIG3EnUOiu25mNcGvTd8EMOuN8qSagda+TYyncafeC8BV
Akv5rXah3od9r1QKFaJPTDSPp/pkjLCfUEp+23CRKolJI3ztj1BVY9iKO3PoXnUR
i4JWZ7NFCqRwp6MZunxoly1pnDNoyMDcog5PF5aafBDVCI7URezbOHsDeeI5eBU9
7PViPLLhAoGBAPI98bnJSWTTKRUp+yLC/PEvsbV5LsCa66gjqAegnxkDlDwKtQwF
RlkqmldszIKUMO2hNfCvWqD9u4t/x7KB15kxshmZ6C4XZFF9DMJD9RsoMTnIFsO9
lpycfijFNgfGcKFpC+TeR/rOP9/FkZOegKtzgliUan/QGGMk76pnxK5tAoGBAM0d
9WSj7alWdFQueY/K6QZfu7wV3nCCXoQgyFafBLeAUYhWFB+TVzc582W5V9P1Vh1a
LRDQb1SLkSkx8iUAQilXGXQLwH7Aqu4K3TJsZ2G0MGY+xw0Rg4w+7OfWj95VppxF
73uK98iOczfoj2qiZUTduCW+kkr0TAc8caPoRX4TAoGBAKsMWldZbl2nTOcI0a/m
Bz029ECz5PNTcPs00j0wiabcBBuxY82tG9NyZbE9vdqmUTY6EyB0cYYkI/2IqLW/
QUGG+b9iEbQaCFgR+KRj3/rhEoE+a/SjNmo3hk27kz9CO919k0x0OFc8s5WKqBSY
YzqtQWjSw7Cke9PmDOVCiHqxAoGBAKNpnrsTLqCeVAdND2PTkFqXooVyFskj1BEH
3RPFlIhtHoezrEyLogxJivQb+TDQYE76LLUcmdWNa5SaSgPYdN1imtCtHCrfbE5B
MYCehK5+U6Dhmst6jIcLCsqZUf0b16Tgwq52RHnvozODf97AilWXHsJTVVGJ15hc
O10OC28pAoGAYoWyIfYcL+lCeqkrrSpefeV1QyKmR3iMrUlXdJUeCBCvDXjpu6m+
oqKZf8EryGjcaZgazrVROjY5BshXWjY14Y5Q4q/0ipLvD9upsydUXdm1ypzIvpwu
Fgo9m2+v7biLMY+fViX7QapzdcwyfwUVxIa4po0BhK3PiS6UbaTAs80=
-----END RSA PRIVATE KEY-----""" 
refresh_token_duration = 2592000 # 30 days (in seconds)
